### ISSUE TITLE
Doesn't work with Flutter Web

### ISSUE THREAD

**Issue by agdsat134** [VGVentures/property_change_notifier#12]
I tried running the example code at pub dev with a new project and I keep getting the following error when running it in Chrome:

```
Error: NoSuchMethodError: '_listeners='
method not found`
Receiver: Instance of 'MyModel'
Arguments: [Instance of 'ObserverList<() => void>']
    at Object.throw_ [as throw] (http://localhost:49489/dart_sdk.js:4463:11)
    at Object.defaultNoSuchMethod (http://localhost:49489/dart_sdk.js:4901:15)
    at main.MyModel.new.noSuchMethod (http://localhost:49489/dart_sdk.js:5938:19)
    at main.MyModel.new.set [_listeners]
    (http://localhost:49489/packages/flutter_property_change_notifier_2/main.dart.lib.js:653:33)        
    at main.MyModel.new.change_notifier.ChangeNotifier.new
    (http://localhost:49489/packages/flutter/src/foundation/change_notifier.dart.lib.js:98:22)
    at main.MyModel.new.PropertyChangeNotifier.new
    (http://localhost:49489/packages/property_change_notifier/src/property_change_notifier.dart.lib.js:1    30:44)
    at main.MyModel.new.Object_PropertyChangeNotifier$36.new
    (http://localhost:49489/packages/flutter_property_change_notifier_2/main.dart.lib.js:628:84)        
    at new main.MyModel.new
    (http://localhost:49489/packages/flutter_property_change_notifier_2/main.dart.lib.js:659:32)        
    at new main.MyApp.new
    (http://localhost:49489/packages/flutter_property_change_notifier_2/main.dart.lib.js:730:19)        
    at Object.main$ [as main]
    (http://localhost:49489/packages/flutter_property_change_notifier_2/main.dart.lib.js:915:27)        
    at main$ (http://localhost:49489/web_entrypoint.dart.lib.js:14:12)
    at main$.next (<anonymous>)
    at http://localhost:49489/dart_sdk.js:37175:33
    at _RootZone.runUnary (http://localhost:49489/dart_sdk.js:37029:58)
    at _FutureListener.thenAwait.handleValue (http://localhost:49489/dart_sdk.js:32116:29)
    at handleValueCallback (http://localhost:49489/dart_sdk.js:32663:49)
    at Function._propagateToListeners (http://localhost:49489/dart_sdk.js:32701:17)
    at async._AsyncCallbackEntry.new.callback (http://localhost:49489/dart_sdk.js:32427:27)
    at Object._microtaskLoop (http://localhost:49489/dart_sdk.js:37290:13)
    at _startMicrotaskLoop (http://localhost:49489/dart_sdk.js:37296:13)
    at http://localhost:49489/dart_sdk.js:32918:9
```

**Comment by martinrybak** [comment]
Hm, I just tried running the example project in Chrome and it worked fine. Might be something else on your end. Thanks.
